### PR TITLE
Allow for empty bodies

### PR DESCRIPTION
**Pull request by mkanoor**
Some of the post might not have a body, return an empty hash
if the body is empty

### CODE REVIEW

**Comment by mkanoor** [comment]
@bdunne 
Not sure how to get it to fail by passing in other valid JSON strings the parsing works but it fails with
#<NoMethodError: undefined method `with_indifferent_access' for "1":String>
when we call 
ActionController::Parameters.new(parsed_body).permit!

I have tried the spec with 
```
post("/api/v1.0/authentications", :headers => headers, :params => "1".to_json)
```
It only hits that exception when I pass in an empty string which we are short circuiting now.

**Comment by Fryguy** [comment]
@mkanoor What is the use case for empty bodies?  I can't think of one place where you would want to respond with nothing.

**Comment by bdunne** [comment]
> @bdunne
> Not sure how to get it to fail by passing in other valid JSON strings the parsing works but it fails with
> #<NoMethodError: undefined method `with_indifferent_access' for "1":String>
> when we call
> ActionController::Parameters.new(parsed_body).permit!
> 
> I have tried the spec with
> 
> ```
> post("/api/v1.0/authentications", :headers => headers, :params => "1".to_json)
> ```
> 
> It only hits that exception when I pass in an empty string which we are short circuiting now.

Maybe something like: `post("/api/v1.0/authentications", :headers => headers, :params => "{\"a\":\"z}")

**Comment by mkanoor** [comment]
@bdunne 
That gets trapped before it gets to us
ActionDispatch::Http::Parameters::ParseError:
in 
```
.gem/ruby/2.4.4/gems/actionpack-5.2.3/lib/action_dispatch/http/parameters.rb:117:in `rescue in parse_formatted_parameters'
```

**Comment by mkanoor** [comment]
@bdunne Do we need our code isn'r RAILS already doing all the parsing for us here
https://github.com/rails/rails/blob/84496b85cbb9933b2a2638b74ecf49c6295136c3/actionpack/lib/action_dispatch/http/parameters.rb#L50

**Comment by Fryguy** [comment]
Since Rails is the one catching in valid JSON values (when Content-Type: application/json is passed), then we don't really need to test that pat, technically, but we may want to separately create a PR that ensures that path returns a 400 Bad Request error.  Since we also accept payloads where application/json is not set, I think that's the test we need to add here.

**Comment by mkanoor** [comment]
@Fryguy @bdunne 
Added a test for invalid text data

**Pull request merged**
