### PR TITLE
Move OpenAPI and Filtering to manageiq-api-common

### PR DESCRIPTION
**Pull request by abellotti**
Moving the OpenAPI 3.0.0 and Filtering libraries from Topological Inventory to Common API
    
This includes the following ManageIQ::API::Common
- Filter
- OpenApi
- ErrorDocument
    
Modules and related classes.

### CODE REVIEW

**Comment by gmcculloug** [comment]
cc @lindgrenj6

**Comment by abellotti** [comment]
@gtanzillo had to move one more thing here, the ErrorDocument class which is used by the Filtering logic. please take a 👀 Thanks!

**Comment by abellotti** [comment]
argh, marking back as WIP, content is good but somehow only one commit [PATCH] was brought in per file and not preserving the history.

**Comment by abellotti** [comment]
ping @gtanzillo when you get a chance. 🙇

**Comment by gmcculloug** [comment]
@abellotti Are there a reference or examples of the filtering syntax?

**Comment by abellotti** [comment]
Hi @gmcculloug 

Here are the filters I've used during the Demo.   Showing the query based one and the other client/Faraday based parameters:

- "?filter[name]=reviews", {:filter => { :name => "reviews" }}
- "?filter[name][eq]=reviews", {:filter => { :name => { :eq => "reviews" } }}
- "?filter[name][starts_with]=a", {:filter => { :name => { :starts_with => "a" } }}
- "?filter[name][ends_with]=manager", {:filter => { :name => { :ends_with => "manager" } }}
- "?filter[name][contains]=openshift", {:filter => { :name => { :contains => "openshift" } }}
- "?filter[id]=5", {:filter => { :id => "5" }}
- "?filter[id][eq]=5", {:filter => { :id => { :eq => "5" }}}
- "?filter[id][gt]=180", {:filter => { :id => { :gt => "180" }}}
- "?filter[id][gte]=190", {:filter => { :id => { :gte => "190" }}}
- "?filter[id][lt]=5", {:filter => { :id => { :lt => "5" }}} 
- "?filter[id][lte]=5", {:filter => { :id => { :lte => "5" }}}
- **"?filter[id][]=5&filter[id][]=10&filter[id][]=15&filter[id][]=20", {:filter => { :id => ["5", "10", "15", "20"]}}**
- **"?filter[id][eq][]=5&filter[id][eq][]=10&filter[id][eq][]=15&filter[id][eq][]=20", {:filter => { :id => { :eq => ["5", "10", "15", "20"]}}}**
- "?filter[archived_at][nil]", {:filter => { :archived_at => { :nil => true }}}
- "?filter[archived_at][not_nil]", {:filter => { :archived_at => { :not_nil => true }}}
- "?filter[archived_at][gt]=2019-04-04T00:00:00", {:filter => { :archived_at => { :gt => "2019-04-04T00:00:00" }}}
- "?filter[archived_at][lt]=2019-04-03T16:51:00", {:filter => { :archived_at => { :lt => "2019-04-03T16:51:00" }}}
- "?filter[archived_at][gt]=2019-04-02&filter[archived_at][lt]=2019-04-05", {:filter => { :archived_at => { :gt => "2019-04-02", :lt => "2019-04-05" }}}

The default ruby client has issues with the bulk queries shown in bold, Faraday has no issues with properly serializing those filters.

**Pull request merged**
